/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReserveRouteImport } from './routes/reserve'
import { Route as ReceptionRouteImport } from './routes/reception'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChefRouteImport } from './routes/chef'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackSessionIdRouteImport } from './routes/track.$sessionId'
import { Route as MenuTableIdRouteImport } from './routes/menu.$tableId'

const ReserveRoute = ReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionRoute = ReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefRoute = ChefRouteImport.update({
  id: '/chef',
  path: '/chef',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackSessionIdRoute = TrackSessionIdRouteImport.update({
  id: '/track/$sessionId',
  path: '/track/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuTableIdRoute = MenuTableIdRouteImport.update({
  id: '/menu/$tableId',
  path: '/menu/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chef': typeof ChefRoute
  '/login': typeof LoginRoute
  '/reception': typeof ReceptionRoute
  '/reserve': typeof ReserveRoute
  '/menu/$tableId': typeof MenuTableIdRoute
  '/track/$sessionId': typeof TrackSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chef': typeof ChefRoute
  '/login': typeof LoginRoute
  '/reception': typeof ReceptionRoute
  '/reserve': typeof ReserveRoute
  '/menu/$tableId': typeof MenuTableIdRoute
  '/track/$sessionId': typeof TrackSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chef': typeof ChefRoute
  '/login': typeof LoginRoute
  '/reception': typeof ReceptionRoute
  '/reserve': typeof ReserveRoute
  '/menu/$tableId': typeof MenuTableIdRoute
  '/track/$sessionId': typeof TrackSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/chef'
    | '/login'
    | '/reception'
    | '/reserve'
    | '/menu/$tableId'
    | '/track/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/chef'
    | '/login'
    | '/reception'
    | '/reserve'
    | '/menu/$tableId'
    | '/track/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/chef'
    | '/login'
    | '/reception'
    | '/reserve'
    | '/menu/$tableId'
    | '/track/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ChefRoute: typeof ChefRoute
  LoginRoute: typeof LoginRoute
  ReceptionRoute: typeof ReceptionRoute
  ReserveRoute: typeof ReserveRoute
  MenuTableIdRoute: typeof MenuTableIdRoute
  TrackSessionIdRoute: typeof TrackSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reserve': {
      id: '/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof ReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception': {
      id: '/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof ReceptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef': {
      id: '/chef'
      path: '/chef'
      fullPath: '/chef'
      preLoaderRoute: typeof ChefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$sessionId': {
      id: '/track/$sessionId'
      path: '/track/$sessionId'
      fullPath: '/track/$sessionId'
      preLoaderRoute: typeof TrackSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$tableId': {
      id: '/menu/$tableId'
      path: '/menu/$tableId'
      fullPath: '/menu/$tableId'
      preLoaderRoute: typeof MenuTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ChefRoute: ChefRoute,
  LoginRoute: LoginRoute,
  ReceptionRoute: ReceptionRoute,
  ReserveRoute: ReserveRoute,
  MenuTableIdRoute: MenuTableIdRoute,
  TrackSessionIdRoute: TrackSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
